blank_issues_enabled: false

contact_links:
  - name: ğŸŒ English Issues
    url: https://github.com/misaka10032w/Han1meViewer/issues/new?template=bug_report.en.md
    about: Please report issues in English

  - name: ä¸­æ–‡é—®é¢˜åé¦ˆ
    url: https://github.com/misaka10032w/Han1meViewer/issues/new?template=bug_report.zh-CN.md
    about: è¯·ä½¿ç”¨ä¸­æ–‡åé¦ˆé—®é¢˜

  - name: ç¹é«”ä¸­æ–‡å•é¡Œå›é¥‹
    url: https://github.com/misaka10032w/Han1meViewer/issues/new?template=bug_report.zh-TW.md
    about: è«‹ä½¿ç”¨ç¹é«”ä¸­æ–‡å›é¥‹å•é¡Œ

  - name: Feature Request
    url: https://github.com/misaka10032w/Han1meViewer/issues/new?template=feature_request.en.md
    about: Suggest an idea to improve Han1meViewer

  - name: åŠŸèƒ½è¯·æ±‚
    url: https://github.com/misaka10032w/Han1meViewer/issues/new?template=feature_request.zh-CN.md
    about: å»ºè®®ä¸€ä¸ªæ–°åŠŸèƒ½æ¥æ”¹å–„ Han1meViewer

  - name: åŠŸèƒ½è«‹æ±‚
    url: https://github.com/misaka10032w/Han1meViewer/issues/new?template=feature_request.zh-TW.md
    about: å»ºè­°ä¸€å€‹åŠŸèƒ½ä¾†æ”¹å–„ Han1meViewer