blank_issues_enabled: false

contact_links:
  - name: 其他讨论请移步至讨论区
    url: https://github.com/misaka10032w/Han1meViewer/discussions
    about: Please move to the discussion area for further discussion.